[package]
name = "swu-api"
version = "0.1.0"
authors = ["Johannes <johannes.kreutle111@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
